### ISSUE TITLE
[fix] 폰트 letterSpacing 통일 및 누락된 폰트 사이즈 추가

### ISSUE THREAD

**Issue by halfmoon-mind** [DaITssu/daitssu-client#11]
- TEXT_STYLES 내에 존재하는 스타일 중, 일부 폰트가 letterSpacing이 동일하게 적용되지 않는 문제를 발견했습니다.
- Figma에 올라와 있는 폰트 중, 일부 폰트가 누락된 문제를 발견했습니다.

예시)
```typescript
//Nav M 10
  NavM10: {
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: -0.11,
    fontFamily: 'Pretendard',
  },
  //Caption R 12
  CapR12: {
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: -0.132, // letterSpacing이 모두 -0.11로 설정해야합니다.
    fontFamily: 'Pretendard',
  },
  //Caption M 12
  CapM12: {
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: -0.132,
    fontFamily: 'Pretendard',
  },
```

**Comment by kweonsikyung** [comment]
확인해봤는데,  letterSpacing은 -1.1%이고, 코드는 px로 작성했기 때문에 해당 부분은 현재 올바르게 작성된 것 같습니당. (폰트 사이즈가 텍스트 스타일 마다 다르기 때문에  letterSpacing도 다르게 나오는 것 참고해주세요!)

**Comment by kweonsikyung** [comment]
폰트는 프리텐다드 모두 넣어뒀는데, 폰트사이즈가 14 이하에서 안 먹고 있네요 ㅜ 현재는 원인을 모르겠어서 해당 부분 다시 확인해보겠슴당

**Comment by halfmoon-mind** [comment]
사이즈 안먹는건 확인해주시고 결과 바로 디스코드로 찍어 주세요
